spring.application.name=fila-api
spring.datasource.url=jdbc:mysql://localhost:3306/sus_fila_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Lel@uch1.

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
zapi.instanceId=3F2AF6DD46D6E3B183B876F7F124D212
zapi.token=BEAC114B1D1C9BE2BC0C4913
zapi.clientToken=F2b7d5272efab4a1e8adf579e0e3510c8S